#!/bin/bash

# n8n Production Setup Script
# This script generates secure passwords and creates all config files

set -e

echo "🚀 Setting up n8n production environment..."

# Check if .env already exists
if [ -f ".env" ]; then
    echo "⚠️  Configuration file .env already exists."
    read -p "Do you want to overwrite it? (y/N): " confirm
    if [ "$confirm" != "y" ] && [ "$confirm" != "Y" ]; then
        echo "Aborted."
        exit 1
    fi
fi

# Generate secure passwords
echo "🔐 Generating secure passwords..."
DB_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)
REDIS_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)
ENCRYPTION_KEY=$(openssl rand -hex 32)

echo "📁 Creating configuration files..."

# Create .env
cat > .env << EOF
# ==============================================================================
#                         n8n Production Environment
# ==============================================================================
# Generated by setup.sh on $(date)

# ==============================================================================
#                              CREDENTIALS
# ==============================================================================

# Database
POSTGRES_USER=n8n_user
POSTGRES_PASSWORD=${DB_PASSWORD}
POSTGRES_DB=n8n

# Redis
REDIS_PASSWORD=${REDIS_PASSWORD}

# n8n Encryption (MUST be unique and kept secret)
N8N_ENCRYPTION_KEY=${ENCRYPTION_KEY}

# ==============================================================================
#                              DATABASE
# ==============================================================================
POSTGRES_HOST=postgres
POSTGRES_PORT=5432
DATABASE_URL=postgres://n8n_user:${DB_PASSWORD}@postgres:5432/n8n

# n8n Database Connection (via PgBouncer)
DB_TYPE=postgresdb
DB_POSTGRESDB_HOST=pgbouncer
DB_POSTGRESDB_PORT=6432
DB_POSTGRESDB_DATABASE=n8n
DB_POSTGRESDB_USER=n8n_user
DB_POSTGRESDB_PASSWORD=${DB_PASSWORD}

# ==============================================================================
#                              PGBOUNCER
# ==============================================================================
PGBOUNCER_LISTEN_PORT=6432
PGBOUNCER_LISTEN_ADDR=0.0.0.0
PGBOUNCER_AUTH_TYPE=md5
PGBOUNCER_AUTH_FILE=/etc/pgbouncer/userlist.txt
PGBOUNCER_MAX_CLIENT_CONN=1000
PGBOUNCER_POOL_MODE=transaction
PGBOUNCER_DEFAULT_POOL_SIZE=50
PGBOUNCER_MIN_POOL_SIZE=5
PGBOUNCER_RESERVE_POOL_SIZE=20
PGBOUNCER_RESERVE_POOL_TIMEOUT=5

# ==============================================================================
#                              REDIS / QUEUE
# ==============================================================================
EXECUTIONS_MODE=queue
QUEUE_BULL_REDIS_HOST=redis
QUEUE_BULL_REDIS_PASSWORD=${REDIS_PASSWORD}
QUEUE_HEALTH_CHECK_ACTIVE=true

# ==============================================================================
#                              N8N SETTINGS
# ==============================================================================
NODE_ENV=production

# URLs - UPDATE THESE FOR YOUR DOMAIN
N8N_HOST=n8n.yourdomain.com
N8N_PORT=5678
N8N_PROTOCOL=https
N8N_EDITOR_BASE_URL=https://n8n.yourdomain.com
WEBHOOK_URL=https://n8n-webhook.yourdomain.com

# Security
N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
N8N_BLOCK_ENV_ACCESS_IN_NODE=true
N8N_DISABLE_PRODUCTION_MAIN_PROCESS=true
N8N_SECURE_COOKIE=true

# Task Runners (for Code nodes)
N8N_RUNNERS_ENABLED=true
N8N_RUNNERS_MODE=internal

# Execution Settings
EXECUTIONS_TIMEOUT=3600
EXECUTIONS_DATA_SAVE_ON_ERROR=all
EXECUTIONS_DATA_SAVE_ON_SUCCESS=all
EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS=true
EXECUTIONS_DATA_PRUNE=true
EXECUTIONS_DATA_MAX_AGE=168

# Timezone
GENERIC_TIMEZONE=Asia/Tehran
TZ=Asia/Tehran
EOF

# Create pgbouncer.ini
cat > pgbouncer.ini << EOF
[databases]
# N8N database through PgBouncer
n8n = host=postgres port=5432 dbname=n8n user=n8n_user password=${DB_PASSWORD}

[pgbouncer]
# Listening configuration
listen_addr = 0.0.0.0
listen_port = 6432
unix_socket_dir = /tmp

# Authentication
auth_type = md5
auth_file = /etc/pgbouncer/userlist.txt

# Pool settings
pool_mode = transaction
max_client_conn = 1000
default_pool_size = 50
min_pool_size = 5
reserve_pool_size = 20
reserve_pool_timeout = 5
EOF

# Create userlist.txt
cat > userlist.txt << EOF
"n8n_user" "${DB_PASSWORD}"
EOF

echo ""
echo "✅ Setup complete!"
echo ""
echo "📋 Generated credentials (save these securely!):"
echo "   Database Password: ${DB_PASSWORD}"
echo "   Redis Password:    ${REDIS_PASSWORD}"
echo "   Encryption Key:    ${ENCRYPTION_KEY}"
echo ""
echo "⚠️  IMPORTANT: Update the domain settings in .env:"
echo "   - N8N_HOST"
echo "   - N8N_EDITOR_BASE_URL"
echo "   - WEBHOOK_URL"
echo ""
echo "🚀 To start the services, run:"
echo "   docker compose up -d"
